issuance-service:
  image:
    pullPolicy: Always

  ingress:
   enabled: true
   ingressClassName: traefik
   annotations:
     cert-manager.io/cluster-issuer: letsencrypt-prod
     traefik.ingress.kubernetes.io/router.middlewares: NAMESPACE-rewrite-issuance-credential@kubernetescrd
   hosts:
     - host: cloud-wallet.DOMAIN
       paths:
         - path: /api/issuance/credential
           port: 8080
           pathtype: Exact
   tls:
     - secretName: xfsc-wildcard
       hosts:
         - cloud-wallet.DOMAIN

  config:
    jwksUrl: https://auth-cloud-wallet.DOMAIN/realms/master/protocol/openid-connect/certs
    audience: https://cloud-wallet.DOMAIN
    nats:
      url: nats://nats.NAMESPACE.svc.cluster.local:4222
      timeoutInSec: 10
    logLevel: info
    servingPort: 8080
