---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-diddocument-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Release.Namespace }}-headers-did-document@kubernetescrd,{{ .Release.Namespace }}-rewrite-did-document@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
      - path: /.well-known/did.json
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Values.ingress.service.backend }}
            port:
              number: {{ .Values.ingress.service.port }}
  {{ if .Values.ingress.tls }}
  tls:
  - hosts:
      - {{ .Values.ingress.hostname }}
    secretName: {{ .Values.ingress.tls.secret }}
  {{ end }}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-diddconfig-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Release.Namespace }}-headers-did-configuration@kubernetescrd,{{ .Release.Namespace }}-rewrite-did-configuration@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
      - path: /.well-known/did-configuration.json
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Values.ingress.service.backend }}
            port:
              number: {{ .Values.ingress.service.port }}

  {{ if .Values.ingress.tls }}
  tls:
  - hosts:
      - {{ .Values.ingress.hostname }}
    secretName: {{ .Values.ingress.tls.secret }}
  {{ end }}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-didjwk-ingress
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: {{ .Release.Namespace }}-headers-jwks@kubernetescrd,{{ .Release.Namespace }}-rewrite-jwks@kubernetescrd
spec:
  ingressClassName: traefik
  rules:
  - host: {{ .Values.ingress.hostname }}
    http:
      paths:
      - path: /.well-known/jwks.json
        pathType: ImplementationSpecific
        backend:
          service:
            name: {{ .Values.ingress.service.backend }}
            port:
              number: {{ .Values.ingress.service.port }}
  {{ if .Values.ingress.tls }}
  tls:
  - hosts:
      - {{ .Values.ingress.hostname }}
    secretName: {{ .Values.ingress.tls.secret }}
  {{ end}}
