credential-retrieval-service:
  replicaCount: 1
  name: credential-retrieval-service

  image:
    repository: node-654e3bca7fbeeed18f81d7c7.ps-xaas.io/ocm-wstack
    name: credential-retrieval-service
    tag: "latest"
    pullPolicy: Always

  podAnnotations: {}
  service:
    port: 8080
    type: ClusterIP
    addr: 0.0.0.0
  resources:
  security:
    runAsNonRoot: false
    runAsUid: 1000
    runAsGid: 1000

  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      traefik.ingress.kubernetes.io/router.middlewares: NAMESPACE-rewrite-offering@kubernetescrd,NAMESPACE-buffering-2k@kubernetescrd
    hosts:
      - host: cloud-wallet.DOMAIN
        paths:
          - path: /api/offering(/|$)(.*)
            port: 8080
            pathType: ImplementationSpecific

    tls:
      - secretName: xfsc-wildcard
        hosts:
          - cloud-wallet.DOMAIN
  config:
    disableTLS: true
    country: DE
    region: EU
    signerTopic: signer-topic
    storageTopic: storage.service.store
    offeringTopic: offering
    offeringPolicy:
    metadataPolicy:
    nats:
      url: nats://nats.NAMESPACE.svc.cluster.local:4222
      queuegroup: offering
      requestTimeOut: 10s
    cassandra:
      hosts: cassandra.NAMESPACE.svc.cluster.local:9042
      keyspace: tenant_space
      user: cassandra
      passwordSecret: cassandra
      passwordKey: cassandra-password
