status-list-service:
  replicaCount: 1
  name: status-list-service

  image:
    repository: node-654e3bca7fbeeed18f81d7c7.ps-xaas.io/ocm-wstack
    name: status-list-service
    tag: "latest"
    sha: ""
    pullPolicy: Always
    pullSecrets: key

  podAnnotations: {}

  resources:
    requests:
      cpu: 25m
      memory: 64Mi
    limits:
      cpu: 150m
      memory: 128Mi

  ingress:
    enabled: true
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      traefik.ingress.kubernetes.io/router.middlewares: NAMESPACE-headers-status-list@kubernetescrd,NAMESPACE-rewrite-status@kubernetescrd
    hosts:
      - host: cloud-wallet.DOMAIN
        paths:
          - path: /api/status(/|$)(.*)
            port: 8080
            pathType: ImplementationSpecific

    tls:
      - secretName: xfsc-wildcard
        hosts:
          - cloud-wallet.DOMAIN

  config:
    messaging:
      protocol: nats
      nats:
        url: http://nats.NAMESPACE.svc.cluster.local:4222
        timeoutInSec: 10s
        queueGroup: statuslistservice
    servingPort: 8083
    database:
      secretName: statuslist-db-secret
      userkey: postgresql-username
      passwordKey: postgresql-password
      host: postgres-rw.NAMESPACE.svc.cluster.local    
      port: 5432
      db: status
      params: "sslmode:disable"
    creationTopic: status
    listSizeInBytes: 125000
    signerTopic: signer

  postgresql:
    auth:
      username: user
      database: status
