well-known-service:
  image: 
    pullPolicy: Always
  ingress:
   enabled: true
   ingressClassName: traefik
   annotations:
     cert-manager.io/cluster-issuer: letsencrypt-prod
     traefik.ingress.kubernetes.io/router.middlewares: NAMESPACE-rewrite-openid-credential-issuer@kubernetescrd
   hosts:
     - host: cloud-wallet.DOMAIN
       paths:
         - path: /.well-known/openid-credential-issuer
           pathtype: ImplementationSpecific
           port: 8080
   tls:
     - secretName: xfsc-wildcard
       hosts:
         - cloud-wallet.DOMAIN
  config:
    loglevel: DEBUG
    isdev: false
    postgres:
      host: postgres-rw.postgres.svc.cluster.local
      port: 5432
      database: wellknown
      user: wellknown
      password:
        key: postgresql-password
        name: wellknown-db-secret
      params: sslmode:disable
    nats:
      url: nats.NAMESPACE.svc.cluster.local:4222
      queuegroup: wellknown
    issuer: cloud-wallet.DOMAIN
    importer:
      broadcast:
