storage-service:  
  replicaCount: 1
  name: storage-service

  image:
    repository: node-654e3bca7fbeeed18f81d7c7.ps-xaas.io/ocm-wstack
    imagePullPolicy: Always
    name: storage-service
    tag: main

  podAnnotations: {}

  resources:
    # requests:
    #   cpu: 25m
    #   memory: 64Mi
    # limits:
    #   cpu: 150m
    #   memory: 128Mi

  service:
    port: 8080
    type: ClusterIP

  cors:
    active: true
    origins: "*"

  server:
    http:
      port: 8080
      address: 0.0.0.0

  ingress:
    enabled: false
    ingressClassName: traefik
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      traefik.ingress.kubernetes.io/router.middlewares: NAMESPACE-rewrite-storage@kubernetescrd,NAMESPACE-buffering-2k@kubernetescrd
    hosts:
      - host:
        paths:
          - path: /storage(/|$)(.*)
            port: 8080
    tls:
      - secretName: xfsc-wildcard
        hosts:
          - cloud-wallet.DOMAIN
  security:
    runAsNonRoot: false
    runAsUid: 1000
    runAsGid: 1000
  config:
    port: 8080
    cassandra:
      hosts: cassandra.NAMESPACE.svc.cluster.local:9042
      keyspace: tenant_space
      user: cassandra
      passwordSecret: cassandra
      passwordKey: cassandra-password
    crypto:
      signKey: storagekey
      namespace: NAMESPACE
    service:
      profiles: API
      country: DE
      region: EU
      mode: DIRECT
    messaging:
      enabled: true
      storageTopic: storage.service.store
      host: nats://nats.NAMESPACE.svc.cluster.local:4222
      protocol: nats
      queueGroup: storage-service
    vault:
      address: http://vault.NAMESPACE.svc.cluster.local:8200
      tokenName: vault
      tokenKey: token
